package diagnosis

import (
	"context"
	"fmt"
	"log/slog"
	"regexp"
	"strings"

	"github.com/lazy-diagnose-k8s/internal/config"
	"github.com/lazy-diagnose-k8s/internal/domain"
)

// Engine performs evidence normalization, hypothesis scoring, and summarization.
type Engine struct {
	rules      *config.PlaybookRules
	summarizer *Summarizer
	logger     *slog.Logger
}

// New creates a new diagnosis engine.
func New(rules *config.PlaybookRules) *Engine {
	return &Engine{rules: rules, logger: slog.Default()}
}

// WithSummarizer sets the LLM summarizer. When set, summaries are generated by Claude API.
func (e *Engine) WithSummarizer(s *Summarizer) *Engine {
	e.summarizer = s
	return e
}

// WithLogger sets the logger.
func (e *Engine) WithLogger(l *slog.Logger) *Engine {
	e.logger = l
	return e
}

// HasSummarizer returns true if LLM summarizer is configured.
func (e *Engine) HasSummarizer() bool { return e.summarizer != nil }

// SummarizeWithLLM sends evidence to LLM for free-form analysis (AI Investigation mode).
func (e *Engine) SummarizeWithLLM(ctx context.Context, intent domain.Intent, bundle *domain.EvidenceBundle) (string, error) {
	if e.summarizer == nil {
		return "", fmt.Errorf("LLM summarizer not configured")
	}
	// Create a minimal result for the summarizer
	scores := e.scoreHypotheses(e.rulesForIntent(intent), bundle)
	sortScores(scores)
	result := &domain.DiagnosisResult{Target: bundle.Target}
	if len(scores) > 0 && scores[0].Score > 0 {
		result.PrimaryHypothesis = &scores[0]
	}
	result.Confidence = e.calculateConfidence(scores, bundle)
	return e.summarizer.Summarize(ctx, intent, bundle, result)
}

// DiagnoseWithoutLLM runs diagnosis with template summary only — no LLM call.
func (e *Engine) DiagnoseWithoutLLM(ctx context.Context, intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	rules := e.rulesForIntent(intent)
	scores := e.scoreHypotheses(rules, bundle)
	sortScores(scores)

	result := &domain.DiagnosisResult{Target: bundle.Target}
	if len(scores) > 0 && scores[0].Score > 0 {
		result.PrimaryHypothesis = &scores[0]
		for _, s := range scores[1:] {
			if s.Score > 0 {
				result.AlternativeHypotheses = append(result.AlternativeHypotheses, s)
			}
		}
	}

	// Fallback: if no hypothesis matched but K8s shows clear issues, infer from raw facts
	if result.PrimaryHypothesis == nil {
		result.PrimaryHypothesis = e.inferFromFacts(bundle)
	}

	result.Confidence = e.calculateConfidence(scores, bundle)
	result.SupportingEvidence = RedactSlice(e.collectEvidence(bundle))
	result.Notes = e.collectNotes(bundle)
	result.Summary = e.summarize(intent, result, bundle)
	return result
}

// Diagnose scores hypotheses and produces a DiagnosisResult.
func (e *Engine) Diagnose(intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	return e.DiagnoseWithContext(context.Background(), intent, bundle)
}

// DiagnoseWithContext scores hypotheses and produces a DiagnosisResult with context for LLM calls.
func (e *Engine) DiagnoseWithContext(ctx context.Context, intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	rules := e.rulesForIntent(intent)
	scores := e.scoreHypotheses(rules, bundle)

	// Sort by score descending
	sortScores(scores)

	result := &domain.DiagnosisResult{
		Target: bundle.Target,
	}

	if len(scores) > 0 && scores[0].Score > 0 {
		result.PrimaryHypothesis = &scores[0]
		if len(scores) > 1 {
			for _, s := range scores[1:] {
				if s.Score > 0 {
					result.AlternativeHypotheses = append(result.AlternativeHypotheses, s)
				}
			}
		}
	}

	// Fallback: if no hypothesis matched but K8s shows clear issues, infer from raw facts
	if result.PrimaryHypothesis == nil {
		result.PrimaryHypothesis = e.inferFromFacts(bundle)
	}

	result.Confidence = e.calculateConfidence(scores, bundle)
	result.SupportingEvidence = RedactSlice(e.collectEvidence(bundle))
	result.Notes = e.collectNotes(bundle)

	// Try LLM summary first, fallback to template
	if e.summarizer != nil {
		e.logger.Info("generating summary",
			"source", "llm",
			"backend", e.summarizer.Backend(),
			"model", e.summarizer.ModelName(),
		)
		llmSummary, err := e.summarizer.Summarize(ctx, intent, bundle, result)
		if err != nil {
			e.logger.Warn("LLM summarizer failed, falling back to template",
				"backend", e.summarizer.Backend(),
				"model", e.summarizer.ModelName(),
				"error", err,
			)
			result.Summary = e.summarize(intent, result, bundle)
		} else {
			e.logger.Info("summary generated",
				"source", "llm",
				"backend", e.summarizer.Backend(),
				"model", e.summarizer.ModelName(),
			)
			result.Summary = llmSummary
		}
	} else {
		e.logger.Info("generating summary", "source", "template")
		result.Summary = e.summarize(intent, result, bundle)
	}

	return result
}

func (e *Engine) rulesForIntent(intent domain.Intent) []config.HypothesisRule {
	switch intent {
	case domain.IntentCrashLoop:
		return e.rules.CrashLoop
	case domain.IntentPending:
		return e.rules.Pending
	case domain.IntentRolloutRegression:
		return e.rules.RolloutRegression
	default:
		return e.rules.CrashLoop // fallback
	}
}

func (e *Engine) scoreHypotheses(rules []config.HypothesisRule, bundle *domain.EvidenceBundle) []domain.HypothesisScore {
	var scores []domain.HypothesisScore

	for _, rule := range rules {
		score := domain.HypothesisScore{
			ID:   rule.ID,
			Name: rule.Name,
		}

		for _, signal := range rule.Signals {
			score.MaxScore += signal.Weight
			if e.matchSignal(signal, bundle) {
				score.Score += signal.Weight
				score.Signals = append(score.Signals, signal.Name)
			}
		}

		scores = append(scores, score)
	}

	return scores
}

func (e *Engine) matchSignal(signal config.SignalRule, bundle *domain.EvidenceBundle) bool {
	switch signal.Source {
	case "k8s":
		return e.matchK8sSignal(signal, bundle.K8sFacts)
	case "logs":
		return e.matchLogsSignal(signal, bundle.LogsFacts)
	case "metrics":
		return e.matchMetricsSignal(signal, bundle.MetricsFacts)
	default:
		return false
	}
}

func (e *Engine) matchK8sSignal(signal config.SignalRule, facts *domain.K8sFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Check container statuses
	for _, pod := range facts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if containsAny(cs.Reason, matchStr) || containsAny(cs.LastTermination, matchStr) || containsAny(cs.State, matchStr) {
				return true
			}
		}
		// Check restart count
		if strings.Contains(matchStr, "restart_count") && pod.RestartCount > 5 {
			return true
		}
	}

	// Check events
	for _, ev := range facts.Events {
		if matchesPattern(ev.Message, matchStr) || matchesPattern(ev.Reason, matchStr) {
			return true
		}
	}

	// Check conditions
	for _, cond := range facts.Conditions {
		if matchesPattern(cond.Message, matchStr) || matchesPattern(cond.Reason, matchStr) {
			return true
		}
	}

	// Check rollout status
	if facts.RolloutStatus != nil {
		rs := facts.RolloutStatus
		if strings.Contains(matchStr, "ready_replicas < desired_replicas") {
			// Check if rollout is stuck: updated pods < desired, or unavailable > 0
			if rs.ReadyReplicas < rs.DesiredReplicas ||
				rs.UnavailableReplicas > 0 ||
				rs.UpdatedReplicas < rs.DesiredReplicas {
				return true
			}
		}
		if strings.Contains(matchStr, "revision unchanged") {
			// No new revision = no recent deploy
			if rs.CurrentRevision == "1" || rs.UpdatedReplicas == rs.DesiredReplicas {
				return true
			}
		}
	}

	// Check if any pod has ImagePullBackOff or ErrImagePull (common in bad deploys)
	for _, pod := range facts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if containsAny(cs.Reason, matchStr) {
				return true
			}
		}
	}

	return false
}

func (e *Engine) matchLogsSignal(signal config.SignalRule, facts *domain.LogsFacts) bool {
	if facts == nil {
		return false
	}

	// Check top errors against pattern
	for _, pattern := range facts.TopErrors {
		if matchesPattern(pattern.Pattern, signal.Match) || matchesPattern(pattern.Sample, signal.Match) {
			return true
		}
	}

	// Check recent lines
	for _, line := range facts.RecentLines {
		if matchesPattern(line, signal.Match) {
			return true
		}
	}

	return false
}

func (e *Engine) matchMetricsSignal(signal config.SignalRule, facts *domain.MetricsFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Memory near limit
	if strings.Contains(matchStr, "memory_usage") && facts.MemoryUsage != nil && facts.MemoryLimit != nil {
		if *facts.MemoryLimit > 0 {
			ratio := *facts.MemoryUsage / *facts.MemoryLimit
			if strings.Contains(matchStr, "90%") && ratio > 0.9 {
				return true
			}
			if strings.Contains(matchStr, "85%") && ratio > 0.85 {
				return true
			}
		}
	}

	// CPU near limit
	if strings.Contains(matchStr, "cpu_usage") && facts.CPUUsage != nil && facts.CPULimit != nil {
		if *facts.CPULimit > 0 {
			ratio := *facts.CPUUsage / *facts.CPULimit
			if ratio > 0.9 {
				return true
			}
		}
	}

	// Error rate spike
	if strings.Contains(matchStr, "error_rate") && facts.ErrorRate != nil && facts.ErrorRateBefore != nil {
		if *facts.ErrorRateBefore > 0 {
			ratio := *facts.ErrorRate / *facts.ErrorRateBefore
			if strings.Contains(matchStr, "2") && ratio > 2.0 {
				return true
			}
		}
	}

	return false
}

func (e *Engine) calculateConfidence(scores []domain.HypothesisScore, bundle *domain.EvidenceBundle) domain.Confidence {
	if len(scores) == 0 || scores[0].Score == 0 {
		return domain.ConfidenceLow
	}

	topScore := scores[0].Score
	base := domain.ConfidenceLow

	if topScore >= 70 {
		base = domain.ConfidenceHigh
	} else if topScore >= 40 {
		base = domain.ConfidenceMedium
	}

	// Degrade confidence if missing data sources
	if !bundle.HasLogs() || !bundle.HasMetrics() {
		if base == domain.ConfidenceHigh {
			base = domain.ConfidenceMedium
		} else if base == domain.ConfidenceMedium {
			base = domain.ConfidenceLow
		}
	}

	return base
}

func (e *Engine) collectEvidence(bundle *domain.EvidenceBundle) []string {
	var evidence []string

	if bundle.K8sFacts != nil {
		for _, pod := range bundle.K8sFacts.PodStatuses {
			evidence = append(evidence, fmt.Sprintf("Pod %s: phase=%s, restarts=%d", pod.Name, pod.Phase, pod.RestartCount))
			for _, cs := range pod.ContainerStatuses {
				if cs.Reason != "" {
					evidence = append(evidence, fmt.Sprintf("  Container %s: state=%s, reason=%s, exit_code=%d", cs.Name, cs.State, cs.Reason, cs.ExitCode))
				}
			}
		}
		for _, ev := range bundle.K8sFacts.Events {
			if ev.Type == "Warning" {
				evidence = append(evidence, fmt.Sprintf("Event [%s]: %s (x%d)", ev.Reason, ev.Message, ev.Count))
			}
		}
		if bundle.K8sFacts.RolloutStatus != nil {
			rs := bundle.K8sFacts.RolloutStatus
			evidence = append(evidence, fmt.Sprintf("Rollout: revision=%s, desired=%d, ready=%d, updated=%d, unavailable=%d",
				rs.CurrentRevision, rs.DesiredReplicas, rs.ReadyReplicas, rs.UpdatedReplicas, rs.UnavailableReplicas))
		}
		if bundle.K8sFacts.ResourceRequests != nil {
			rr := bundle.K8sFacts.ResourceRequests
			evidence = append(evidence, fmt.Sprintf("Resources: cpu=%s/%s, memory=%s/%s", rr.CPURequest, rr.CPULimit, rr.MemoryRequest, rr.MemoryLimit))
		}
	}

	if bundle.LogsFacts != nil {
		for _, pattern := range bundle.LogsFacts.TopErrors {
			evidence = append(evidence, fmt.Sprintf("Log pattern: \"%s\" (x%d)", pattern.Pattern, pattern.Count))
		}
	}

	if bundle.MetricsFacts != nil {
		if bundle.MetricsFacts.MemoryUsage != nil && bundle.MetricsFacts.MemoryLimit != nil {
			usageMi := *bundle.MetricsFacts.MemoryUsage / (1024 * 1024)
			limitMi := *bundle.MetricsFacts.MemoryLimit / (1024 * 1024)
			evidence = append(evidence, fmt.Sprintf("Memory: %.0fMi / %.0fMi (%.0f%%)", usageMi, limitMi, usageMi/limitMi*100))
		}
		if bundle.MetricsFacts.RestartRate != nil {
			evidence = append(evidence, fmt.Sprintf("Restart rate: %.1f/min", *bundle.MetricsFacts.RestartRate))
		}
	}

	return evidence
}

func (e *Engine) summarize(intent domain.Intent, result *domain.DiagnosisResult, bundle *domain.EvidenceBundle) string {
	if result.PrimaryHypothesis == nil {
		return "No clear anomaly detected. Check manually using the commands below."
	}

	var b strings.Builder
	h := result.PrimaryHypothesis

	switch intent {
	case domain.IntentCrashLoop:
		b.WriteString(e.summarizeCrashLoop(h, bundle))
	case domain.IntentPending:
		b.WriteString(e.summarizePending(h, bundle))
	case domain.IntentRolloutRegression:
		b.WriteString(e.summarizeRollout(h, bundle))
	default:
		b.WriteString(fmt.Sprintf("Root cause: %s.", h.Name))
	}

	return b.String()
}

func (e *Engine) summarizeCrashLoop(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "oom_resource":
		// Memory info from metrics or resource limits
		if bundle.MetricsFacts != nil && bundle.MetricsFacts.MemoryLimit != nil {
			limitMi := *bundle.MetricsFacts.MemoryLimit / (1024 * 1024)
			parts = append(parts, fmt.Sprintf("Container OOMKilled — memory limit <code>%.0fMi</code>.", limitMi))
		} else if bundle.K8sFacts != nil && bundle.K8sFacts.ResourceRequests != nil && bundle.K8sFacts.ResourceRequests.MemoryLimit != "" {
			parts = append(parts, fmt.Sprintf("Container OOMKilled — memory limit <code>%s</code>.", bundle.K8sFacts.ResourceRequests.MemoryLimit))
		} else {
			parts = append(parts, "Container OOMKilled — exceeded memory limit.")
		}
		// Restart count + OOM event
		if bundle.K8sFacts != nil {
			for _, pod := range bundle.K8sFacts.PodStatuses {
				if pod.RestartCount > 0 {
					parts = append(parts, fmt.Sprintf("Restarted <b>%d</b> times.", pod.RestartCount))
					break
				}
			}
			// Show OOM event if available
			for _, ev := range bundle.K8sFacts.Events {
				if strings.Contains(strings.ToLower(ev.Message), "oom") || strings.Contains(strings.ToLower(ev.Reason), "oom") {
					parts = append(parts, fmt.Sprintf("Event: %s.", truncateStr(ev.Message, 120)))
					break
				}
			}
		}
		parts = append(parts, "Increase memory limit or fix memory leak.")

	case "config_env_missing":
		parts = append(parts, "Container crashes on startup — missing config or environment variable.")
		// Show relevant log
		if bundle.LogsFacts != nil && len(bundle.LogsFacts.TopErrors) > 0 {
			parts = append(parts, fmt.Sprintf("Log: %s.", truncateStr(bundle.LogsFacts.TopErrors[0].Sample, 150)))
		}
		// Show event (e.g. BackOff)
		if ev := findEventByReason(bundle, "BackOff", "Failed"); ev != "" {
			parts = append(parts, fmt.Sprintf("Event: %s.", truncateStr(ev, 120)))
		}

	case "dependency_connectivity":
		parts = append(parts, "Container can't reach dependency.")
		// Show specific connection error from logs
		if bundle.LogsFacts != nil && len(bundle.LogsFacts.TopErrors) > 0 {
			parts = append(parts, fmt.Sprintf("Log: %s.", truncateStr(bundle.LogsFacts.TopErrors[0].Sample, 150)))
		}
		// Show BackOff event
		if ev := findEventByReason(bundle, "BackOff"); ev != "" {
			parts = append(parts, fmt.Sprintf("Event: %s.", truncateStr(ev, 120)))
		}

	case "probe_issue":
		parts = append(parts, "Container killed by probe failure.")
		// Find specific probe event
		if bundle.K8sFacts != nil {
			for _, ev := range bundle.K8sFacts.Events {
				msg := strings.ToLower(ev.Message)
				if strings.Contains(msg, "liveness probe failed") {
					parts = append(parts, fmt.Sprintf("Event: \"%s\".", truncateStr(ev.Message, 120)))
					break
				}
				if strings.Contains(msg, "readiness probe failed") {
					parts = append(parts, fmt.Sprintf("Event: \"%s\".", truncateStr(ev.Message, 120)))
					break
				}
			}
		}
		parts = append(parts, "Check probe config — initialDelaySeconds may be too short or endpoint not responding.")

	case "bad_image":
		parts = append(parts, e.summarizeBadImage(bundle)...)

	default:
		parts = append(parts, fmt.Sprintf("Container in CrashLoop. Root cause: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

func (e *Engine) summarizeBadImage(bundle *domain.EvidenceBundle) []string {
	if bundle.K8sFacts == nil {
		return []string{"Container can't pull image."}
	}

	// Find the image name from container statuses
	imageName := ""
	for _, pod := range bundle.K8sFacts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if cs.Reason == "ErrImagePull" || cs.Reason == "ImagePullBackOff" {
				// Image name isn't in ContainerStatus, check events
				break
			}
		}
	}

	// Parse events for specific error reason
	for _, ev := range bundle.K8sFacts.Events {
		msg := ev.Message
		lower := strings.ToLower(msg)

		switch {
		case strings.Contains(lower, "manifest unknown") || strings.Contains(lower, "not found"):
			// Extract image name from event message
			if img := extractImageFromEvent(msg); img != "" {
				imageName = img
			}
			return []string{
				fmt.Sprintf("Image tag does not exist: <code>%s</code>.", imageName),
				"Verify the tag is published in the registry.",
			}

		case strings.Contains(lower, "unauthorized") || strings.Contains(lower, "denied") || strings.Contains(lower, "forbidden"):
			if img := extractImageFromEvent(msg); img != "" {
				imageName = img
			}
			return []string{
				fmt.Sprintf("Authentication failed pulling <code>%s</code>.", imageName),
				"Check imagePullSecrets and registry credentials.",
			}

		case strings.Contains(lower, "no such host") || strings.Contains(lower, "lookup") || strings.Contains(lower, "dial tcp"):
			if img := extractImageFromEvent(msg); img != "" {
				imageName = img
			}
			return []string{
				fmt.Sprintf("Registry unreachable for <code>%s</code>.", imageName),
				"Check registry hostname and network/DNS connectivity.",
			}

		case strings.Contains(lower, "failed to pull image") || strings.Contains(lower, "errimagepull"):
			if img := extractImageFromEvent(msg); img != "" {
				imageName = img
			}
			return []string{
				fmt.Sprintf("Failed to pull image <code>%s</code>.", imageName),
				fmt.Sprintf("Event: \"%s\".", truncateStr(msg, 150)),
			}
		}
	}

	return []string{"Container can't pull image. Check events for details."}
}

// extractImageFromEvent tries to pull image reference from event messages like:
// 'Failed to pull image "nginx:v99.99.99-does-not-exist": rpc error...'
func extractImageFromEvent(msg string) string {
	// Look for quoted image name
	start := strings.Index(msg, "\"")
	if start >= 0 {
		end := strings.Index(msg[start+1:], "\"")
		if end >= 0 {
			return msg[start+1 : start+1+end]
		}
	}
	return ""
}

// findEventByReason searches for an event matching any of the given reasons.
func findEventByReason(bundle *domain.EvidenceBundle, reasons ...string) string {
	if bundle.K8sFacts == nil {
		return ""
	}
	for _, ev := range bundle.K8sFacts.Events {
		for _, reason := range reasons {
			if strings.EqualFold(ev.Reason, reason) {
				return ev.Message
			}
		}
	}
	return ""
}

// findSchedulerEvent returns the most relevant FailedScheduling event message.
func findSchedulerEvent(bundle *domain.EvidenceBundle) string {
	if bundle.K8sFacts == nil {
		return ""
	}
	for _, ev := range bundle.K8sFacts.Events {
		if ev.Reason == "FailedScheduling" {
			return ev.Message
		}
	}
	return ""
}

func truncateStr(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max] + "..."
}

func (e *Engine) summarizePending(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "insufficient_resources":
		parts = append(parts, "Pod can't be scheduled — insufficient cluster resources.")
		if bundle.K8sFacts != nil && bundle.K8sFacts.ResourceRequests != nil {
			rr := bundle.K8sFacts.ResourceRequests
			parts = append(parts, fmt.Sprintf("Pod requests: CPU=%s, Memory=%s.", rr.CPURequest, rr.MemoryRequest))
		}
		// Show scheduler event
		if detail := findSchedulerEvent(bundle); detail != "" {
			parts = append(parts, fmt.Sprintf("Scheduler: %s.", truncateStr(detail, 150)))
		}
		parts = append(parts, "Scale up cluster or reduce resource requests.")

	case "taint_mismatch":
		parts = append(parts, "Pod can't be scheduled — node has taint that pod doesn't tolerate.")
		if detail := findSchedulerEvent(bundle); detail != "" {
			parts = append(parts, fmt.Sprintf("Scheduler: %s.", truncateStr(detail, 150)))
		}
		parts = append(parts, "Add toleration or remove taint from node.")

	case "affinity_issue":
		parts = append(parts, "Pod can't be scheduled — no node matches affinity/nodeSelector.")
		if detail := findSchedulerEvent(bundle); detail != "" {
			parts = append(parts, fmt.Sprintf("Scheduler: %s.", truncateStr(detail, 150)))
		}

	case "pvc_binding":
		parts = append(parts, "Pod stuck Pending — PersistentVolumeClaim can't bind.")
		parts = append(parts, "Check PV availability and StorageClass provisioner.")

	case "quota_issue":
		parts = append(parts, "Pod blocked by ResourceQuota — namespace quota exhausted.")

	default:
		parts = append(parts, fmt.Sprintf("Pod Pending. Root cause: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

func (e *Engine) summarizeRollout(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "release_regression":
		parts = append(parts, "New rollout has issues.")
		if bundle.K8sFacts != nil && bundle.K8sFacts.RolloutStatus != nil {
			rs := bundle.K8sFacts.RolloutStatus
			parts = append(parts, fmt.Sprintf("Revision %s: %d/%d pods ready, %d unavailable.",
				rs.CurrentRevision, rs.ReadyReplicas, rs.DesiredReplicas, rs.UnavailableReplicas))
		}
		// Check for image pull errors
		if bundle.K8sFacts != nil {
			for _, pod := range bundle.K8sFacts.PodStatuses {
				for _, cs := range pod.ContainerStatuses {
					if cs.Reason == "ErrImagePull" || cs.Reason == "ImagePullBackOff" {
						parts = append(parts, "New pod stuck in ImagePullBackOff — check image tag.")
						goto doneImageCheck
					}
				}
			}
		}
	doneImageCheck:
		parts = append(parts, "Consider rollback if service is impacted.")

	case "dependency_exposed":
		parts = append(parts, "New release may have exposed a pre-existing dependency bug.")

	case "traffic_spike_unrelated":
		parts = append(parts, "Traffic spike detected — may be unrelated to the release.")

	case "resource_pressure":
		parts = append(parts, "New release increased resource consumption — container hitting limits.")

	default:
		parts = append(parts, fmt.Sprintf("Rollout issue detected. Root cause: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

// inferFromFacts attempts to determine the issue directly from K8s facts + logs
// when no playbook hypothesis scored above 0. This prevents "No anomaly" on obvious issues.
func (e *Engine) inferFromFacts(bundle *domain.EvidenceBundle) *domain.HypothesisScore {
	if bundle.K8sFacts == nil {
		return nil
	}

	var signals []string

	// Check container statuses for obvious issues
	for _, pod := range bundle.K8sFacts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			switch {
			case cs.Reason == "OOMKilled" || cs.LastTermination == "OOMKilled":
				return &domain.HypothesisScore{
					ID: "oom_resource", Name: "OOM / Resource exhaustion",
					Score: 40, MaxScore: 90, Signals: []string{"container_oomkilled"},
				}
			case cs.Reason == "CrashLoopBackOff":
				signals = append(signals, "crashloop_detected")
			case cs.Reason == "ErrImagePull" || cs.Reason == "ImagePullBackOff":
				return &domain.HypothesisScore{
					ID: "bad_image", Name: "Bad image / Startup failure",
					Score: 60, MaxScore: 90, Signals: []string{"image_pull_error"},
				}
			case cs.Reason == "CreateContainerConfigError":
				return &domain.HypothesisScore{
					ID: "config_env_missing", Name: "Config / Env missing",
					Score: 50, MaxScore: 70, Signals: []string{"config_error"},
				}
			case cs.ExitCode == 1 && cs.State == "terminated":
				signals = append(signals, "exit_code_1")
			}
		}
	}

	// Check events for clues
	for _, ev := range bundle.K8sFacts.Events {
		msg := strings.ToLower(ev.Message)
		if strings.Contains(msg, "liveness probe failed") || strings.Contains(msg, "readiness probe failed") {
			return &domain.HypothesisScore{
				ID: "probe_issue", Name: "Probe misconfiguration",
				Score: 50, MaxScore: 70, Signals: []string{"probe_failed_event"},
			}
		}
		if strings.Contains(msg, "failedscheduling") {
			return &domain.HypothesisScore{
				ID: "insufficient_resources", Name: "Insufficient cluster resources",
				Score: 60, MaxScore: 90, Signals: []string{"failedscheduling_event"},
			}
		}
	}

	// Check logs for error patterns (direct scan, not relying on playbook rules)
	if bundle.LogsFacts != nil && len(bundle.LogsFacts.TopErrors) > 0 {
		topError := strings.ToLower(bundle.LogsFacts.TopErrors[0].Pattern)
		switch {
		case strings.Contains(topError, "env not found") || strings.Contains(topError, "missing required") ||
			strings.Contains(topError, "config error") || strings.Contains(topError, "undefined variable") ||
			strings.Contains(topError, "not set"):
			return &domain.HypothesisScore{
				ID: "config_env_missing", Name: "Config / Env missing",
				Score: 50, MaxScore: 70, Signals: append(signals, "error_log_config"),
			}
		case strings.Contains(topError, "connection refused") || strings.Contains(topError, "timeout") ||
			strings.Contains(topError, "dial tcp") || strings.Contains(topError, "ECONNREFUSED"):
			return &domain.HypothesisScore{
				ID: "dependency_connectivity", Name: "Dependency / Connectivity issue",
				Score: 40, MaxScore: 80, Signals: append(signals, "error_log_connectivity"),
			}
		case strings.Contains(topError, "permission denied") || strings.Contains(topError, "access denied"):
			return &domain.HypothesisScore{
				ID: "config_env_missing", Name: "Permission / Auth error",
				Score: 40, MaxScore: 70, Signals: append(signals, "error_log_permission"),
			}
		}
	}

	// Check raw recent log lines too (TopErrors might miss patterns)
	if bundle.LogsFacts != nil {
		for _, line := range bundle.LogsFacts.RecentLines {
			lower := strings.ToLower(line)
			if strings.Contains(lower, "missing required") || strings.Contains(lower, "not set") ||
				strings.Contains(lower, "config validation failed") || strings.Contains(lower, "env") && strings.Contains(lower, "fatal") {
				return &domain.HypothesisScore{
					ID: "config_env_missing", Name: "Config / Env missing",
					Score: 50, MaxScore: 70, Signals: append(signals, "log_line_config_error"),
				}
			}
			if strings.Contains(lower, "connection refused") || strings.Contains(lower, "dial tcp") {
				return &domain.HypothesisScore{
					ID: "dependency_connectivity", Name: "Dependency / Connectivity issue",
					Score: 40, MaxScore: 80, Signals: append(signals, "log_line_connectivity"),
				}
			}
		}
	}

	// If CrashLoop detected but no specific cause found, return generic crash hypothesis
	if len(signals) > 0 {
		return &domain.HypothesisScore{
			ID: "unknown_crash", Name: "Container crash (check logs)",
			Score: 20, MaxScore: 100, Signals: signals,
		}
	}

	return nil
}

func (e *Engine) collectNotes(bundle *domain.EvidenceBundle) []string {
	var notes []string
	for _, ps := range bundle.ProviderStatuses {
		if !ps.Available {
			notes = append(notes, fmt.Sprintf("⚠ Provider '%s' unavailable: %s. Results may be incomplete.", ps.Name, ps.Error))
		}
	}
	if !bundle.HasMetrics() {
		notes = append(notes, "Missing metrics data. Confidence degraded.")
	}
	if !bundle.HasLogs() {
		notes = append(notes, "Missing logs data. Confidence degraded.")
	}
	return notes
}

// --- helpers ---

func containsAny(text, pattern string) bool {
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	return false
}

func matchesPattern(text, pattern string) bool {
	// First try simple contains for each | separated part
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	// Try regex
	re, err := regexp.Compile("(?i)" + pattern)
	if err != nil {
		return false
	}
	return re.MatchString(text)
}

func sortScores(scores []domain.HypothesisScore) {
	for i := 0; i < len(scores); i++ {
		for j := i + 1; j < len(scores); j++ {
			if scores[j].Score > scores[i].Score {
				scores[i], scores[j] = scores[j], scores[i]
			}
		}
	}
}
