package diagnosis

import (
	"context"
	"fmt"
	"log/slog"
	"regexp"
	"strings"

	"github.com/lazy-diagnose-k8s/internal/config"
	"github.com/lazy-diagnose-k8s/internal/domain"
)

// Engine performs evidence normalization, hypothesis scoring, and summarization.
type Engine struct {
	rules      *config.PlaybookRules
	summarizer *Summarizer
	logger     *slog.Logger
}

// New creates a new diagnosis engine.
func New(rules *config.PlaybookRules) *Engine {
	return &Engine{rules: rules, logger: slog.Default()}
}

// WithSummarizer sets the LLM summarizer. When set, summaries are generated by Claude API.
func (e *Engine) WithSummarizer(s *Summarizer) *Engine {
	e.summarizer = s
	return e
}

// WithLogger sets the logger.
func (e *Engine) WithLogger(l *slog.Logger) *Engine {
	e.logger = l
	return e
}

// Diagnose scores hypotheses and produces a DiagnosisResult.
func (e *Engine) Diagnose(intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	return e.DiagnoseWithContext(context.Background(), intent, bundle)
}

// DiagnoseWithContext scores hypotheses and produces a DiagnosisResult with context for LLM calls.
func (e *Engine) DiagnoseWithContext(ctx context.Context, intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	rules := e.rulesForIntent(intent)
	scores := e.scoreHypotheses(rules, bundle)

	// Sort by score descending
	sortScores(scores)

	result := &domain.DiagnosisResult{
		Target: bundle.Target,
	}

	if len(scores) > 0 && scores[0].Score > 0 {
		result.PrimaryHypothesis = &scores[0]
		if len(scores) > 1 {
			for _, s := range scores[1:] {
				if s.Score > 0 {
					result.AlternativeHypotheses = append(result.AlternativeHypotheses, s)
				}
			}
		}
	}

	result.Confidence = e.calculateConfidence(scores, bundle)
	result.SupportingEvidence = RedactSlice(e.collectEvidence(bundle))
	result.Notes = e.collectNotes(bundle)

	// Try LLM summary first, fallback to template
	if e.summarizer != nil {
		llmSummary, err := e.summarizer.Summarize(ctx, intent, bundle, result)
		if err != nil {
			e.logger.Warn("LLM summarizer failed, using template", "error", err)
			result.Summary = e.summarize(intent, result, bundle)
		} else {
			result.Summary = llmSummary
		}
	} else {
		result.Summary = e.summarize(intent, result, bundle)
	}

	return result
}

func (e *Engine) rulesForIntent(intent domain.Intent) []config.HypothesisRule {
	switch intent {
	case domain.IntentCrashLoop:
		return e.rules.CrashLoop
	case domain.IntentPending:
		return e.rules.Pending
	case domain.IntentRolloutRegression:
		return e.rules.RolloutRegression
	default:
		return e.rules.CrashLoop // fallback
	}
}

func (e *Engine) scoreHypotheses(rules []config.HypothesisRule, bundle *domain.EvidenceBundle) []domain.HypothesisScore {
	var scores []domain.HypothesisScore

	for _, rule := range rules {
		score := domain.HypothesisScore{
			ID:   rule.ID,
			Name: rule.Name,
		}

		for _, signal := range rule.Signals {
			score.MaxScore += signal.Weight
			if e.matchSignal(signal, bundle) {
				score.Score += signal.Weight
				score.Signals = append(score.Signals, signal.Name)
			}
		}

		scores = append(scores, score)
	}

	return scores
}

func (e *Engine) matchSignal(signal config.SignalRule, bundle *domain.EvidenceBundle) bool {
	switch signal.Source {
	case "k8s":
		return e.matchK8sSignal(signal, bundle.K8sFacts)
	case "logs":
		return e.matchLogsSignal(signal, bundle.LogsFacts)
	case "metrics":
		return e.matchMetricsSignal(signal, bundle.MetricsFacts)
	default:
		return false
	}
}

func (e *Engine) matchK8sSignal(signal config.SignalRule, facts *domain.K8sFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Check container statuses
	for _, pod := range facts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if containsAny(cs.Reason, matchStr) || containsAny(cs.LastTermination, matchStr) || containsAny(cs.State, matchStr) {
				return true
			}
		}
		// Check restart count
		if strings.Contains(matchStr, "restart_count") && pod.RestartCount > 5 {
			return true
		}
	}

	// Check events
	for _, ev := range facts.Events {
		if matchesPattern(ev.Message, matchStr) || matchesPattern(ev.Reason, matchStr) {
			return true
		}
	}

	// Check conditions
	for _, cond := range facts.Conditions {
		if matchesPattern(cond.Message, matchStr) || matchesPattern(cond.Reason, matchStr) {
			return true
		}
	}

	// Check rollout status
	if facts.RolloutStatus != nil {
		rs := facts.RolloutStatus
		if strings.Contains(matchStr, "ready_replicas < desired_replicas") {
			// Check if rollout is stuck: updated pods < desired, or unavailable > 0
			if rs.ReadyReplicas < rs.DesiredReplicas ||
				rs.UnavailableReplicas > 0 ||
				rs.UpdatedReplicas < rs.DesiredReplicas {
				return true
			}
		}
		if strings.Contains(matchStr, "revision unchanged") {
			// No new revision = no recent deploy
			if rs.CurrentRevision == "1" || rs.UpdatedReplicas == rs.DesiredReplicas {
				return true
			}
		}
	}

	// Check if any pod has ImagePullBackOff or ErrImagePull (common in bad deploys)
	for _, pod := range facts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if containsAny(cs.Reason, matchStr) {
				return true
			}
		}
	}

	return false
}

func (e *Engine) matchLogsSignal(signal config.SignalRule, facts *domain.LogsFacts) bool {
	if facts == nil {
		return false
	}

	// Check top errors against pattern
	for _, pattern := range facts.TopErrors {
		if matchesPattern(pattern.Pattern, signal.Match) || matchesPattern(pattern.Sample, signal.Match) {
			return true
		}
	}

	// Check recent lines
	for _, line := range facts.RecentLines {
		if matchesPattern(line, signal.Match) {
			return true
		}
	}

	return false
}

func (e *Engine) matchMetricsSignal(signal config.SignalRule, facts *domain.MetricsFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Memory near limit
	if strings.Contains(matchStr, "memory_usage") && facts.MemoryUsage != nil && facts.MemoryLimit != nil {
		if *facts.MemoryLimit > 0 {
			ratio := *facts.MemoryUsage / *facts.MemoryLimit
			if strings.Contains(matchStr, "90%") && ratio > 0.9 {
				return true
			}
			if strings.Contains(matchStr, "85%") && ratio > 0.85 {
				return true
			}
		}
	}

	// CPU near limit
	if strings.Contains(matchStr, "cpu_usage") && facts.CPUUsage != nil && facts.CPULimit != nil {
		if *facts.CPULimit > 0 {
			ratio := *facts.CPUUsage / *facts.CPULimit
			if ratio > 0.9 {
				return true
			}
		}
	}

	// Error rate spike
	if strings.Contains(matchStr, "error_rate") && facts.ErrorRate != nil && facts.ErrorRateBefore != nil {
		if *facts.ErrorRateBefore > 0 {
			ratio := *facts.ErrorRate / *facts.ErrorRateBefore
			if strings.Contains(matchStr, "2") && ratio > 2.0 {
				return true
			}
		}
	}

	return false
}

func (e *Engine) calculateConfidence(scores []domain.HypothesisScore, bundle *domain.EvidenceBundle) domain.Confidence {
	if len(scores) == 0 || scores[0].Score == 0 {
		return domain.ConfidenceLow
	}

	topScore := scores[0].Score
	base := domain.ConfidenceLow

	if topScore >= 70 {
		base = domain.ConfidenceHigh
	} else if topScore >= 40 {
		base = domain.ConfidenceMedium
	}

	// Degrade confidence if missing data sources
	if !bundle.HasLogs() || !bundle.HasMetrics() {
		if base == domain.ConfidenceHigh {
			base = domain.ConfidenceMedium
		} else if base == domain.ConfidenceMedium {
			base = domain.ConfidenceLow
		}
	}

	return base
}

func (e *Engine) collectEvidence(bundle *domain.EvidenceBundle) []string {
	var evidence []string

	if bundle.K8sFacts != nil {
		for _, pod := range bundle.K8sFacts.PodStatuses {
			evidence = append(evidence, fmt.Sprintf("Pod %s: phase=%s, restarts=%d", pod.Name, pod.Phase, pod.RestartCount))
			for _, cs := range pod.ContainerStatuses {
				if cs.Reason != "" {
					evidence = append(evidence, fmt.Sprintf("  Container %s: state=%s, reason=%s, exit_code=%d", cs.Name, cs.State, cs.Reason, cs.ExitCode))
				}
			}
		}
		for _, ev := range bundle.K8sFacts.Events {
			if ev.Type == "Warning" {
				evidence = append(evidence, fmt.Sprintf("Event [%s]: %s (x%d)", ev.Reason, ev.Message, ev.Count))
			}
		}
		if bundle.K8sFacts.RolloutStatus != nil {
			rs := bundle.K8sFacts.RolloutStatus
			evidence = append(evidence, fmt.Sprintf("Rollout: revision=%s, desired=%d, ready=%d, updated=%d, unavailable=%d",
				rs.CurrentRevision, rs.DesiredReplicas, rs.ReadyReplicas, rs.UpdatedReplicas, rs.UnavailableReplicas))
		}
		if bundle.K8sFacts.ResourceRequests != nil {
			rr := bundle.K8sFacts.ResourceRequests
			evidence = append(evidence, fmt.Sprintf("Resources: cpu=%s/%s, memory=%s/%s", rr.CPURequest, rr.CPULimit, rr.MemoryRequest, rr.MemoryLimit))
		}
	}

	if bundle.LogsFacts != nil {
		for _, pattern := range bundle.LogsFacts.TopErrors {
			evidence = append(evidence, fmt.Sprintf("Log pattern: \"%s\" (x%d)", pattern.Pattern, pattern.Count))
		}
	}

	if bundle.MetricsFacts != nil {
		if bundle.MetricsFacts.MemoryUsage != nil && bundle.MetricsFacts.MemoryLimit != nil {
			usageMi := *bundle.MetricsFacts.MemoryUsage / (1024 * 1024)
			limitMi := *bundle.MetricsFacts.MemoryLimit / (1024 * 1024)
			evidence = append(evidence, fmt.Sprintf("Memory: %.0fMi / %.0fMi (%.0f%%)", usageMi, limitMi, usageMi/limitMi*100))
		}
		if bundle.MetricsFacts.RestartRate != nil {
			evidence = append(evidence, fmt.Sprintf("Restart rate: %.1f/min", *bundle.MetricsFacts.RestartRate))
		}
	}

	return evidence
}

func (e *Engine) summarize(intent domain.Intent, result *domain.DiagnosisResult, bundle *domain.EvidenceBundle) string {
	if result.PrimaryHypothesis == nil {
		return "Không tìm thấy dấu hiệu bất thường rõ ràng. Kiểm tra thủ công bằng commands bên dưới."
	}

	var b strings.Builder
	h := result.PrimaryHypothesis

	switch intent {
	case domain.IntentCrashLoop:
		b.WriteString(e.summarizeCrashLoop(h, bundle))
	case domain.IntentPending:
		b.WriteString(e.summarizePending(h, bundle))
	case domain.IntentRolloutRegression:
		b.WriteString(e.summarizeRollout(h, bundle))
	default:
		b.WriteString(fmt.Sprintf("Nguyên nhân: %s.", h.Name))
	}

	return b.String()
}

func (e *Engine) summarizeCrashLoop(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "oom_resource":
		// Find actual memory numbers
		if bundle.MetricsFacts != nil && bundle.MetricsFacts.MemoryLimit != nil {
			limitMi := *bundle.MetricsFacts.MemoryLimit / (1024 * 1024)
			parts = append(parts, fmt.Sprintf("Container bị OOMKilled — đang dùng hết memory limit (%.0fMi).", limitMi))
		} else {
			parts = append(parts, "Container bị OOMKilled — vượt quá memory limit.")
		}
		// Find restart count
		if bundle.K8sFacts != nil {
			for _, pod := range bundle.K8sFacts.PodStatuses {
				if pod.RestartCount > 0 {
					parts = append(parts, fmt.Sprintf("Đã restart %d lần.", pod.RestartCount))
					break
				}
			}
		}
		parts = append(parts, "Cần tăng memory limit hoặc fix memory leak.")

	case "config_env_missing":
		parts = append(parts, "Container crash ngay khi start — thiếu config hoặc environment variable.")
		if bundle.LogsFacts != nil && len(bundle.LogsFacts.TopErrors) > 0 {
			parts = append(parts, fmt.Sprintf("Log: \"%s\".", bundle.LogsFacts.TopErrors[0].Sample))
		}

	case "dependency_connectivity":
		parts = append(parts, "Container không kết nối được tới dependency (connection refused/timeout).")
		if bundle.LogsFacts != nil && len(bundle.LogsFacts.TopErrors) > 0 {
			parts = append(parts, fmt.Sprintf("Log: \"%s\".", bundle.LogsFacts.TopErrors[0].Sample))
		}

	case "probe_issue":
		parts = append(parts, "Container bị kill do liveness/readiness probe fail.")
		parts = append(parts, "Kiểm tra probe config — có thể initialDelaySeconds quá ngắn hoặc endpoint không respond.")

	case "bad_image":
		parts = append(parts, "Container không pull được image — sai tag hoặc thiếu credentials.")

	default:
		parts = append(parts, fmt.Sprintf("Container đang CrashLoop. Nguyên nhân: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

func (e *Engine) summarizePending(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "insufficient_resources":
		parts = append(parts, "Pod không schedule được — cluster thiếu tài nguyên.")
		if bundle.K8sFacts != nil && bundle.K8sFacts.ResourceRequests != nil {
			rr := bundle.K8sFacts.ResourceRequests
			parts = append(parts, fmt.Sprintf("Pod request: CPU=%s, Memory=%s.", rr.CPURequest, rr.MemoryRequest))
		}
		parts = append(parts, "Scale up cluster hoặc giảm resource requests.")

	case "taint_mismatch":
		parts = append(parts, "Pod không schedule được — node có taint mà pod không tolerate.")
		parts = append(parts, "Thêm toleration hoặc remove taint khỏi node.")

	case "affinity_issue":
		parts = append(parts, "Pod không schedule được — không có node nào match affinity/nodeSelector.")

	case "pvc_binding":
		parts = append(parts, "Pod stuck Pending — PersistentVolumeClaim chưa bound được.")
		parts = append(parts, "Kiểm tra PV available và StorageClass provisioner.")

	case "quota_issue":
		parts = append(parts, "Pod bị block bởi ResourceQuota — namespace đã hết quota.")

	default:
		parts = append(parts, fmt.Sprintf("Pod Pending. Nguyên nhân: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

func (e *Engine) summarizeRollout(h *domain.HypothesisScore, bundle *domain.EvidenceBundle) string {
	var parts []string

	switch h.ID {
	case "release_regression":
		parts = append(parts, "Rollout mới có vấn đề.")
		if bundle.K8sFacts != nil && bundle.K8sFacts.RolloutStatus != nil {
			rs := bundle.K8sFacts.RolloutStatus
			parts = append(parts, fmt.Sprintf("Revision %s: %d/%d pods ready, %d unavailable.",
				rs.CurrentRevision, rs.ReadyReplicas, rs.DesiredReplicas, rs.UnavailableReplicas))
		}
		// Check for image pull errors
		if bundle.K8sFacts != nil {
			for _, pod := range bundle.K8sFacts.PodStatuses {
				for _, cs := range pod.ContainerStatuses {
					if cs.Reason == "ErrImagePull" || cs.Reason == "ImagePullBackOff" {
						parts = append(parts, "New pod bị ImagePullBackOff — kiểm tra image tag.")
						goto doneImageCheck
					}
				}
			}
		}
	doneImageCheck:
		parts = append(parts, "Cân nhắc rollback nếu service bị ảnh hưởng.")

	case "dependency_exposed":
		parts = append(parts, "Release mới có thể đã expose bug dependency có sẵn.")

	case "traffic_spike_unrelated":
		parts = append(parts, "Có dấu hiệu traffic spike — có thể không liên quan tới release.")

	case "resource_pressure":
		parts = append(parts, "Release mới tăng resource consumption — container đang chạm limit.")

	default:
		parts = append(parts, fmt.Sprintf("Rollout có vấn đề. Nguyên nhân: %s.", h.Name))
	}

	return strings.Join(parts, " ")
}

func (e *Engine) collectNotes(bundle *domain.EvidenceBundle) []string {
	var notes []string
	for _, ps := range bundle.ProviderStatuses {
		if !ps.Available {
			notes = append(notes, fmt.Sprintf("⚠ Provider '%s' không available: %s. Kết quả có thể không đầy đủ.", ps.Name, ps.Error))
		}
	}
	if !bundle.HasMetrics() {
		notes = append(notes, "Thiếu dữ liệu metrics. Confidence đã được hạ.")
	}
	if !bundle.HasLogs() {
		notes = append(notes, "Thiếu dữ liệu logs. Confidence đã được hạ.")
	}
	return notes
}

// --- helpers ---

func containsAny(text, pattern string) bool {
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	return false
}

func matchesPattern(text, pattern string) bool {
	// First try simple contains for each | separated part
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	// Try regex
	re, err := regexp.Compile("(?i)" + pattern)
	if err != nil {
		return false
	}
	return re.MatchString(text)
}

func sortScores(scores []domain.HypothesisScore) {
	for i := 0; i < len(scores); i++ {
		for j := i + 1; j < len(scores); j++ {
			if scores[j].Score > scores[i].Score {
				scores[i], scores[j] = scores[j], scores[i]
			}
		}
	}
}
