package diagnosis

import (
	"context"
	"fmt"
	"log/slog"
	"regexp"
	"strings"

	"github.com/lazy-diagnose-k8s/internal/config"
	"github.com/lazy-diagnose-k8s/internal/domain"
)

// Engine performs evidence normalization, hypothesis scoring, and summarization.
type Engine struct {
	rules      *config.PlaybookRules
	summarizer *Summarizer
	logger     *slog.Logger
}

// New creates a new diagnosis engine.
func New(rules *config.PlaybookRules) *Engine {
	return &Engine{rules: rules, logger: slog.Default()}
}

// WithSummarizer sets the LLM summarizer. When set, summaries are generated by Claude API.
func (e *Engine) WithSummarizer(s *Summarizer) *Engine {
	e.summarizer = s
	return e
}

// WithLogger sets the logger.
func (e *Engine) WithLogger(l *slog.Logger) *Engine {
	e.logger = l
	return e
}

// Diagnose scores hypotheses and produces a DiagnosisResult.
func (e *Engine) Diagnose(intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	return e.DiagnoseWithContext(context.Background(), intent, bundle)
}

// DiagnoseWithContext scores hypotheses and produces a DiagnosisResult with context for LLM calls.
func (e *Engine) DiagnoseWithContext(ctx context.Context, intent domain.Intent, bundle *domain.EvidenceBundle) *domain.DiagnosisResult {
	rules := e.rulesForIntent(intent)
	scores := e.scoreHypotheses(rules, bundle)

	// Sort by score descending
	sortScores(scores)

	result := &domain.DiagnosisResult{
		Target: bundle.Target,
	}

	if len(scores) > 0 && scores[0].Score > 0 {
		result.PrimaryHypothesis = &scores[0]
		if len(scores) > 1 {
			for _, s := range scores[1:] {
				if s.Score > 0 {
					result.AlternativeHypotheses = append(result.AlternativeHypotheses, s)
				}
			}
		}
	}

	result.Confidence = e.calculateConfidence(scores, bundle)
	result.SupportingEvidence = e.collectEvidence(bundle)
	result.Notes = e.collectNotes(bundle)

	// Try LLM summary first, fallback to template
	if e.summarizer != nil {
		llmSummary, err := e.summarizer.Summarize(ctx, intent, bundle, result)
		if err != nil {
			e.logger.Warn("LLM summarizer failed, using template", "error", err)
			result.Summary = e.summarize(intent, result, bundle)
		} else {
			result.Summary = llmSummary
		}
	} else {
		result.Summary = e.summarize(intent, result, bundle)
	}

	return result
}

func (e *Engine) rulesForIntent(intent domain.Intent) []config.HypothesisRule {
	switch intent {
	case domain.IntentCrashLoop:
		return e.rules.CrashLoop
	case domain.IntentPending:
		return e.rules.Pending
	case domain.IntentRolloutRegression:
		return e.rules.RolloutRegression
	default:
		return e.rules.CrashLoop // fallback
	}
}

func (e *Engine) scoreHypotheses(rules []config.HypothesisRule, bundle *domain.EvidenceBundle) []domain.HypothesisScore {
	var scores []domain.HypothesisScore

	for _, rule := range rules {
		score := domain.HypothesisScore{
			ID:   rule.ID,
			Name: rule.Name,
		}

		for _, signal := range rule.Signals {
			score.MaxScore += signal.Weight
			if e.matchSignal(signal, bundle) {
				score.Score += signal.Weight
				score.Signals = append(score.Signals, signal.Name)
			}
		}

		scores = append(scores, score)
	}

	return scores
}

func (e *Engine) matchSignal(signal config.SignalRule, bundle *domain.EvidenceBundle) bool {
	switch signal.Source {
	case "k8s":
		return e.matchK8sSignal(signal, bundle.K8sFacts)
	case "logs":
		return e.matchLogsSignal(signal, bundle.LogsFacts)
	case "metrics":
		return e.matchMetricsSignal(signal, bundle.MetricsFacts)
	default:
		return false
	}
}

func (e *Engine) matchK8sSignal(signal config.SignalRule, facts *domain.K8sFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Check container statuses
	for _, pod := range facts.PodStatuses {
		for _, cs := range pod.ContainerStatuses {
			if containsAny(cs.Reason, matchStr) || containsAny(cs.LastTermination, matchStr) || containsAny(cs.State, matchStr) {
				return true
			}
		}
		// Check restart count
		if strings.Contains(matchStr, "restart_count") && pod.RestartCount > 5 {
			return true
		}
	}

	// Check events
	for _, ev := range facts.Events {
		if matchesPattern(ev.Message, matchStr) || matchesPattern(ev.Reason, matchStr) {
			return true
		}
	}

	// Check conditions
	for _, cond := range facts.Conditions {
		if matchesPattern(cond.Message, matchStr) || matchesPattern(cond.Reason, matchStr) {
			return true
		}
	}

	// Check rollout status
	if facts.RolloutStatus != nil {
		if strings.Contains(matchStr, "ready_replicas < desired_replicas") {
			if facts.RolloutStatus.ReadyReplicas < facts.RolloutStatus.DesiredReplicas {
				return true
			}
		}
	}

	return false
}

func (e *Engine) matchLogsSignal(signal config.SignalRule, facts *domain.LogsFacts) bool {
	if facts == nil {
		return false
	}

	// Check top errors against pattern
	for _, pattern := range facts.TopErrors {
		if matchesPattern(pattern.Pattern, signal.Match) || matchesPattern(pattern.Sample, signal.Match) {
			return true
		}
	}

	// Check recent lines
	for _, line := range facts.RecentLines {
		if matchesPattern(line, signal.Match) {
			return true
		}
	}

	return false
}

func (e *Engine) matchMetricsSignal(signal config.SignalRule, facts *domain.MetricsFacts) bool {
	if facts == nil {
		return false
	}

	matchStr := signal.Match

	// Memory near limit
	if strings.Contains(matchStr, "memory_usage") && facts.MemoryUsage != nil && facts.MemoryLimit != nil {
		if *facts.MemoryLimit > 0 {
			ratio := *facts.MemoryUsage / *facts.MemoryLimit
			if strings.Contains(matchStr, "90%") && ratio > 0.9 {
				return true
			}
			if strings.Contains(matchStr, "85%") && ratio > 0.85 {
				return true
			}
		}
	}

	// CPU near limit
	if strings.Contains(matchStr, "cpu_usage") && facts.CPUUsage != nil && facts.CPULimit != nil {
		if *facts.CPULimit > 0 {
			ratio := *facts.CPUUsage / *facts.CPULimit
			if ratio > 0.9 {
				return true
			}
		}
	}

	// Error rate spike
	if strings.Contains(matchStr, "error_rate") && facts.ErrorRate != nil && facts.ErrorRateBefore != nil {
		if *facts.ErrorRateBefore > 0 {
			ratio := *facts.ErrorRate / *facts.ErrorRateBefore
			if strings.Contains(matchStr, "2") && ratio > 2.0 {
				return true
			}
		}
	}

	return false
}

func (e *Engine) calculateConfidence(scores []domain.HypothesisScore, bundle *domain.EvidenceBundle) domain.Confidence {
	if len(scores) == 0 || scores[0].Score == 0 {
		return domain.ConfidenceLow
	}

	topScore := scores[0].Score
	base := domain.ConfidenceLow

	if topScore >= 70 {
		base = domain.ConfidenceHigh
	} else if topScore >= 40 {
		base = domain.ConfidenceMedium
	}

	// Degrade confidence if missing data sources
	if !bundle.HasLogs() || !bundle.HasMetrics() {
		if base == domain.ConfidenceHigh {
			base = domain.ConfidenceMedium
		} else if base == domain.ConfidenceMedium {
			base = domain.ConfidenceLow
		}
	}

	return base
}

func (e *Engine) collectEvidence(bundle *domain.EvidenceBundle) []string {
	var evidence []string

	if bundle.K8sFacts != nil {
		for _, pod := range bundle.K8sFacts.PodStatuses {
			evidence = append(evidence, fmt.Sprintf("Pod %s: phase=%s, restarts=%d", pod.Name, pod.Phase, pod.RestartCount))
			for _, cs := range pod.ContainerStatuses {
				if cs.Reason != "" {
					evidence = append(evidence, fmt.Sprintf("  Container %s: state=%s, reason=%s, exit_code=%d", cs.Name, cs.State, cs.Reason, cs.ExitCode))
				}
			}
		}
		for _, ev := range bundle.K8sFacts.Events {
			if ev.Type == "Warning" {
				evidence = append(evidence, fmt.Sprintf("Event [%s]: %s (x%d)", ev.Reason, ev.Message, ev.Count))
			}
		}
	}

	if bundle.LogsFacts != nil {
		for _, pattern := range bundle.LogsFacts.TopErrors {
			evidence = append(evidence, fmt.Sprintf("Log pattern: \"%s\" (x%d)", pattern.Pattern, pattern.Count))
		}
	}

	if bundle.MetricsFacts != nil {
		if bundle.MetricsFacts.MemoryUsage != nil && bundle.MetricsFacts.MemoryLimit != nil {
			usageMi := *bundle.MetricsFacts.MemoryUsage / (1024 * 1024)
			limitMi := *bundle.MetricsFacts.MemoryLimit / (1024 * 1024)
			evidence = append(evidence, fmt.Sprintf("Memory: %.0fMi / %.0fMi (%.0f%%)", usageMi, limitMi, usageMi/limitMi*100))
		}
		if bundle.MetricsFacts.RestartRate != nil {
			evidence = append(evidence, fmt.Sprintf("Restart rate: %.1f/min", *bundle.MetricsFacts.RestartRate))
		}
	}

	return evidence
}

func (e *Engine) summarize(intent domain.Intent, result *domain.DiagnosisResult, bundle *domain.EvidenceBundle) string {
	target := bundle.Target.FullName()

	if result.PrimaryHypothesis == nil {
		return fmt.Sprintf("Không xác định được nguyên nhân rõ ràng cho %s. Cần kiểm tra thêm.", target)
	}

	hypothesis := result.PrimaryHypothesis.Name
	confidence := result.Confidence

	switch intent {
	case domain.IntentCrashLoop:
		return fmt.Sprintf("%s đang bị CrashLoop. Nguyên nhân chính: %s (confidence: %s).", target, hypothesis, confidence)
	case domain.IntentPending:
		return fmt.Sprintf("%s đang ở trạng thái Pending. Nguyên nhân: %s (confidence: %s).", target, hypothesis, confidence)
	case domain.IntentRolloutRegression:
		return fmt.Sprintf("%s có dấu hiệu regression sau deploy. Nguyên nhân: %s (confidence: %s).", target, hypothesis, confidence)
	default:
		return fmt.Sprintf("Diagnosis cho %s: %s (confidence: %s).", target, hypothesis, confidence)
	}
}

func (e *Engine) collectNotes(bundle *domain.EvidenceBundle) []string {
	var notes []string
	for _, ps := range bundle.ProviderStatuses {
		if !ps.Available {
			notes = append(notes, fmt.Sprintf("⚠ Provider '%s' không available: %s. Kết quả có thể không đầy đủ.", ps.Name, ps.Error))
		}
	}
	if !bundle.HasMetrics() {
		notes = append(notes, "Thiếu dữ liệu metrics. Confidence đã được hạ.")
	}
	if !bundle.HasLogs() {
		notes = append(notes, "Thiếu dữ liệu logs. Confidence đã được hạ.")
	}
	return notes
}

// --- helpers ---

func containsAny(text, pattern string) bool {
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	return false
}

func matchesPattern(text, pattern string) bool {
	// First try simple contains for each | separated part
	parts := strings.Split(pattern, "|")
	lower := strings.ToLower(text)
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" && strings.Contains(lower, strings.ToLower(p)) {
			return true
		}
	}
	// Try regex
	re, err := regexp.Compile("(?i)" + pattern)
	if err != nil {
		return false
	}
	return re.MatchString(text)
}

func sortScores(scores []domain.HypothesisScore) {
	for i := 0; i < len(scores); i++ {
		for j := i + 1; j < len(scores); j++ {
			if scores[j].Score > scores[i].Score {
				scores[i], scores[j] = scores[j], scores[i]
			}
		}
	}
}
